name: Deploy to NPM

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Setting up Node.js...
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install any dependencies
      - name: Installing npm dependencies...
        run: npm ci
      
      # Attempt a build to ensure that it can be packaged
      - name: Building artifacts...
        run: npm run build

      - name: Uploading artifacts...
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: . 

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pulling build...
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: .

      - name: Deploying to npm...
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
    
